'use strict';

const submitButton = document.getElementById('start');
console.log('submitButton: ', submitButton);
const plus1 = document.getElementsByTagName('button')[0];
console.log('plus1: ', plus1);
const plus2 = document.getElementsByTagName('button')[1];
console.log('plus2: ', plus2);
const checkbox = document.querySelector('#deposit-check');
console.log('checkbox: ', checkbox);
let addIncome = document.querySelectorAll('.additional_income-item');
console.log('addIncome: ', addIncome);
let budgetMonthValue = document.querySelector('.budget_month-value');
console.log('budgetMonthValue: ', budgetMonthValue);
let budgetDayValue = document.querySelector('.budget_day-value');
console.log('budgetDayValue: ', budgetDayValue);
let expensesMonthValue = document.querySelector('.expenses_month-value');
console.log('expensesMonthValue: ', expensesMonthValue);
let addIncomeValue = document.querySelector('.additional_income-value');
console.log('addIncomeValue: ', addIncomeValue);
let addExpensesValue = document.querySelector('.additional_expenses-value');
console.log('addExpensesValue: ', addExpensesValue);
let incomePeriodValue = document.querySelector('.income_period-value');
console.log('incomePeriodValue: ', incomePeriodValue);
let targetMonthValue = document.querySelector('.target_month-value');
console.log('targetMonthValue: ', targetMonthValue);
let salaryAmount = document.querySelector('.salary-amount');
console.log('salaryAmount: ', salaryAmount);
let incomeTitle = document.querySelector('.income-title');
console.log('incomeTitle: ', incomeTitle);
let incomeAmount = document.querySelector('.income-amount');
console.log('incomeAmount: ', incomeAmount);
let additionalIncome1 = document.querySelectorAll('.additional_income-item')[0];
console.log('additionalIncome1: ', additionalIncome1);
let additionalIncome2 = document.querySelectorAll('.additional_income-item')[1];
console.log('additionalIncome2: ', additionalIncome2);
let expensesTitle = document.querySelector('.expenses-title');
console.log('expensesTitle: ', expensesTitle);
let expensesAmount = document.querySelector('.expenses-amount');
console.log('expensesAmount: ', expensesAmount);
let additionalExpItem = document.querySelector('.additional_expenses-item');
console.log('additionalExpItem: ', additionalExpItem);
let targetAmount = document.querySelector('.target-amount');
console.log('targetAmount: ', targetAmount);
let periodSelect = document.querySelector('.period-select');
console.log('periodSelect: ', periodSelect);
